### ISSUE TITLE
apply_acrylic does not display properly in windows 22H2

### ISSUE THREAD

**Issue by minghamn** [amrbashir/tauri-plugin-vibrancy#75]
I tried using this in fltk-rs.
Seems to work only for the menu bar.
I have tried it on windows 22H1 and it is displayed normally.
But this will not work properly in windows 22H2.

```toml
# Cargo.toml
[package]
name = "fltk-acrylic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.3.22", features = ["rwh05"] }
window-vibrancy = "0.3"
```
```rs
# main.rs
use fltk::{prelude::*, *};
use window_vibrancy::apply_acrylic;

fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Gtk);
    let mut win = window::Window::default().with_size(400, 400);
    win.end();
    win.show();

    apply_acrylic(&win, Some((10, 10, 10, 90))).expect("Unsupported");
    a.run().unwrap();
}
```

![image](https://user-images.githubusercontent.com/95327699/205540801-5308a84e-81b1-4d7a-a6bc-1343467d497b.png)
